apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: app
spec:
  template:
    spec: 
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: app
      requirements:
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values: ["c7","m7"]
      - key: karpenter.k8s.aws/instance-size
        operator: NotIn
        values: ["nano","micro","small","medium"] 
      - key: karpenter.k8s.aws/instance-hypervisor
        operator: In
        values: ["nitro"]
      - key: topology.kubernetes.io/zone
        operator: In
        values: ["us-east-1a","us-east-1b"]  
      - key: kubernetes.io/arch
        operator: In
        values: ["amd64","arm64"]
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["spot"]
  limits:
    cpu: "1000m"
    memory: "1000Mi"
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: app
spec:
  amiFamily: AL2
  subnetSelectorTerms:
    - tags:
        kubernetes.io/cluster/eks-karpenter: owned
  securityGroupSelectorTerms:
    - tags:
        kubernetes.io/cluster/eks-karpenter: owned